In [3]:
import pandas as pd
import string

In [21]:
board_data1 = pd.read_csv("../2020_board_data.csv")
board_data1.head()
board_data2 = pd.read_csv("../corp_boards_40_80.csv", header=None)
board_data2.columns = board_data1.columns
board_data2.head()
board_data = pd.concat([board_data1, board_data2], axis=0)

In [22]:
board_data.head()

,Company,2020 Rating,Total Board,# of women,% of Women,Sector,State,City
0,3M CO,NaN,11,2,18%,Industrials,Minnesota,ST. PAUL
1,ABBOTT LABORATORIES,NaN,12,4,33%,Healthcare,Illinois,ABBOTT PARK
2,ADOBE SYSTEMS INC,NaN,10,2,20%,Technology,California,SAN JOSE
3,AFLAC INC,NaN,14,3,21%,Financial Services,Georgia,COLUMBUS
4,AIR PRODUCTS & CHEMICALS INC /DE/,NaN,8,2,25%,Basic Materials,Pennsylvania,ALLENTOWN

In [26]:
board_data['Company_clean'] = board_data['Company'].str.lower()
board_data['Company_clean'] = board_data['Company_clean'].str.replace(" inc", "")
board_data['Company_clean'] = board_data['Company_clean'].str.replace(" inc.", "")
board_data['Company_clean'] = board_data['Company_clean'].str.replace(" co", "")
board_data['Company_clean'] = board_data['Company_clean'].str.replace(" corp", "")
board_data['Company_clean'] = board_data['Company_clean'].str.replace(" /de/", "")
board_data.head()

,Company,2020 Rating,Total Board,# of women,% of Women,Sector,State,City,Company_clean
0,3M CO,NaN,11,2,18%,Industrials,Minnesota,ST. PAUL,3m
1,ABBOTT LABORATORIES,NaN,12,4,33%,Healthcare,Illinois,ABBOTT PARK,abbott laboratories
2,ADOBE SYSTEMS INC,NaN,10,2,20%,Technology,California,SAN JOSE,adobe systems
3,AFLAC INC,NaN,14,3,21%,Financial Services,Georgia,COLUMBUS,aflac
4,AIR PRODUCTS & CHEMICALS INC /DE/,NaN,8,2,25%,Basic Materials,Pennsylvania,ALLENTOWN,air products & chemicals